# Generated by Django 4.0.3 on 2022-06-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapi', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_comment', models.CharField(max_length=100)),
                ('expense_done_on', models.DateField()),
                ('expense_amount', models.IntegerField()),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensesapi.employee')),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensesapi.vendor')),
            ],
        ),
    ]
