# Generated by Django 4.0.3 on 2022-06-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapi', '0003_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expensesapi.employee', to_field='employee_code'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expensesapi.vendor', to_field='vendor_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
